apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: three-tier
type: Opaque
data:
  username: YWRtaW4=                #base64 encode
  password: cGFzc3dvcmQxMjM=        #base64 encode
