apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  selector:
    role: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
